//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracticaKornilovaMarushkina
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.Exame = new HashSet<Exame>();
        }
    
        public int Id_Number { get; set; }
        public string CipherID { get; set; }
        public string LastName { get; set; }
        public Nullable<int> Id_Pozition { get; set; }
        public Nullable<int> Id_Boss { get; set; }
        public Nullable<int> Id_Rank { get; set; }
        public Nullable<int> Id_Degree { get; set; }
    
        public virtual Boss Boss { get; set; }
        public virtual Degree Degree { get; set; }
        public virtual Departament Departament { get; set; }
        public virtual Pozition Pozition { get; set; }
        public virtual Rank Rank { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Exame> Exame { get; set; }
    }
}
