//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracticaKornilovaMarushkina.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Academics
    {
        public int Id_academics { get; set; }
        public string FIO { get; set; }
        public Nullable<System.DateTime> Date_Born { get; set; }
        public Nullable<int> Id_Specialization { get; set; }
        public Nullable<int> Year_rank { get; set; }
    
        public virtual Specialization Specialization { get; set; }
    }
}
