//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracticaKornilovaMarushkina.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country
    {
        public int Id_Country { get; set; }
        public string Name_Country { get; set; }
        public string Capital { get; set; }
        public Nullable<double> Square { get; set; }
        public Nullable<int> Population { get; set; }
        public Nullable<int> Id_Continent { get; set; }
        public Nullable<int> Type_Control { get; set; }
    
        public virtual Continent Continent { get; set; }
        public virtual Type_Control Type_Control1 { get; set; }
    }
}
