//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracticaKornilovaMarushkina.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exame
    {
        public int Id_Exam { get; set; }
        public Nullable<System.DateTime> Date_Exam { get; set; }
        public Nullable<int> Id_Discipline { get; set; }
        public Nullable<int> Id_Student { get; set; }
        public Nullable<int> Id_Teacher { get; set; }
        public string Auditoria { get; set; }
        public Nullable<int> Grade { get; set; }
    
        public virtual Discipline Discipline { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Student Student { get; set; }
    }
}
