//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracticaKornilovaMarushkina.DataBase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Ych_PR_KMEntities1 : DbContext
    {
        public Ych_PR_KMEntities1()
            : base("name=Ych_PR_KMEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Academics> Academics { get; set; }
        public virtual DbSet<Animal_Kornilova_Marushkina> Animal_Kornilova_Marushkina { get; set; }
        public virtual DbSet<Application> Application { get; set; }
        public virtual DbSet<Boss> Boss { get; set; }
        public virtual DbSet<Continent> Continent { get; set; }
        public virtual DbSet<Control_Kornilova_Marushkina> Control_Kornilova_Marushkina { get; set; }
        public virtual DbSet<Countries_Kornilova_Marushkina> Countries_Kornilova_Marushkina { get; set; }
        public virtual DbSet<Country> Country { get; set; }
        public virtual DbSet<Degree> Degree { get; set; }
        public virtual DbSet<Departament> Departament { get; set; }
        public virtual DbSet<Discipline> Discipline { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<Engineer> Engineer { get; set; }
        public virtual DbSet<Exame> Exame { get; set; }
        public virtual DbSet<Faculty> Faculty { get; set; }
        public virtual DbSet<Flowers_Kornilova_Marushkina> Flowers_Kornilova_Marushkina { get; set; }
        public virtual DbSet<Learner> Learner { get; set; }
        public virtual DbSet<Pozition> Pozition { get; set; }
        public virtual DbSet<Rank> Rank { get; set; }
        public virtual DbSet<Spec> Spec { get; set; }
        public virtual DbSet<Speciality> Speciality { get; set; }
        public virtual DbSet<Specialization> Specialization { get; set; }
        public virtual DbSet<Student> Student { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Type_Control> Type_Control { get; set; }
        public virtual DbSet<Гимназисты> Гимназисты { get; set; }
    }
}
